name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8
        cache: 'gradle'

    - name: Gradle Build
      run: ./gradlew build

    - name: Run Demo
      if: github.event_name == 'pull_request'
      run: ./run.sh

    - uses: actions/upload-artifact@v3
      if: github.event_name == 'pull_request'
      with:
        name: custom-report.html
        path: custom-report.html
